# Generated by Django 3.2.13 on 2023-06-13 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('64bd872e-784a-4fa6-9ad7-8230ac0bfc7d'), primary_key=True, serialize=False)),
                ('woreda', models.CharField(max_length=500)),
                ('comments', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='feedbacks/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
