# Generated by Django 3.2.13 on 2023-06-13 20:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_feedback_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d275cfe9-893c-4735-a22c-45e6b3155ec7'), primary_key=True, serialize=False),
        ),
    ]
