# Generated by Django 3.2.13 on 2023-06-13 21:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_feedback_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e8c2b79f-3631-4247-af4d-fcea07e41b98'), primary_key=True, serialize=False),
        ),
    ]
