# Generated by Django 3.2.13 on 2023-06-17 07:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_feedback_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e68549f8-7af8-48c6-bc07-aa350b251c3b'), primary_key=True, serialize=False),
        ),
    ]
