# Generated by Django 4.1.7 on 2023-06-18 00:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0005_alter_feedback_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("8caf55cc-e107-420f-8511-6f8fca903f70"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
