# Generated by Django 4.1.7 on 2023-06-18 00:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0006_alter_feedback_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
