# Generated by Django 4.1.7 on 2023-06-18 16:35

import django.core.validators
from django.db import migrations, models
import review.models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0007_alter_feedback_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="feedbacks/",
                validators=[
                    django.core.validators.FileExtensionValidator([".pdf"]),
                    review.models.validate_fil_mimetype,
                ],
            ),
        ),
    ]
