# Generated by Django 3.2.13 on 2023-06-13 20:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('72d6ae76-bc96-4548-b256-da8b3c63559c'), primary_key=True, serialize=False),
        ),
    ]
