# Generated by Django 3.2.13 on 2023-06-13 20:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('f0020d3b-4770-45d8-b2e5-a376a7dd5669'), primary_key=True, serialize=False),
        ),
    ]
