# Generated by Django 3.2.13 on 2023-06-13 21:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('2829877c-1c27-40f2-bf0a-47c09f574dc2'), primary_key=True, serialize=False),
        ),
    ]
