# Generated by Django 3.2.13 on 2023-06-17 07:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('4bd576e9-fc14-4c1e-9376-054eaea40f3f'), primary_key=True, serialize=False),
        ),
    ]
