# Generated by Django 4.1.7 on 2023-06-18 00:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID("709accb4-7967-45fa-82a9-acbfb4194bf4"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
