# Generated by Django 4.1.7 on 2023-06-18 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
